### ISSUE TITLE
Default location

### ISSUE THREAD

**Issue by jackperth** [P72B/Mocklation#2]
Hi,
Great App ☺
I was wondering if there was a way to start a specific location by default when the App launches.

I'm experimenting with an app which automates various settings when the device is started, I would like to be able to test it at a particular location.

I can automate Moclation to start at device power-on but can't find a way to initiate a presaved location.

Kind regards,
Jack

**Comment by AKprisonER** [comment]
we can mention the co-ordinates in string file, so by inputting at mocklation, u can update default location.
Also editing the location can be done, so that user can change it to different location,
